#!/bin/bash          
echo "now installing cutycapt"

sudo apt-get update -y
sudo apt-get install build-essential -y
sudo apt-get install xvfb -y
sudo apt-get install xfs xfonts-scalable xfonts-100dpi -y
sudo apt-get install libgl1-mesa-dri -y
sudo apt-get install subversion libqt4-webkit libqt4-dev g++ -y

sudo mkdir /opt/scripts
cd /opt/scripts
sudo svn co https://svn.code.sf.net/p/cutycapt/code/CutyCapt
cd CutyCapt

sudo qmake
sudo make

xvfb-run --auto-servernum --server-args="-screen 0, 1024x768x24" ./CutyCapt --url=http://www.google.com --out=example.png
